stages:
  - build
  - test

build:
  stage: build
  tags:
    - fit2107-runner
  image: python:3.8-alpine
  script:
    - echo "Building"

test:
  stage: test
  tags:
    - fit2107-runner
  image: python:3.8-alpine
  script:
    - echo "Testing"
    - pip3 install -r requirements.txt
    - pip3 install coverage
    - coverage run -m unittest test/test_calculator.py
    - coverage report -m
    - coverage html -d coverage_reports
  artifacts:
    paths:
      - coverage_reports/